[package]
name = "nanopub-js"
version = "0.1.0"
authors = ["Vincent Emonet <vincent.emonet@gmail.com>"]
description = "JavaScript bindings for the Nanopub rust toolkit"
license = "MIT"
repository = "https://github.com/vemonet/nanopub-rs/tree/main/js"
homepage = "https://github.com/vemonet/nanopub-rs"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
console_error_panic_hook = "0.1"
nanopub = { path = "../lib" }

[dev-dependencies]
wasm-bindgen-test = "0.3"