# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
        name: 🐘 Check for added large files
    -   id: check-toml
        name: ✔️  Check TOML
    -   id: check-yaml
        name: ✔️  Check YAML
        args:
        -   --unsafe
    -   id: end-of-file-fixer
        name: 🪚 Fix end of files
    -   id: trailing-whitespace
        name: ✂️  Trim trailing whitespaces
-   repo: https://github.com/crate-ci/typos
    rev: v1.19.0
    hooks:
    -   id: typos
        name: ✒️  Check typos
        exclude: ^lib/docs/docs/assets/orcid-widget.js$
-   repo: local
    hooks:
      - id: rustfmt
        name: 🦀 Format Rust files
        description: Check if all files follow the rustfmt style
        entry: cargo fmt
        language: system
        pass_filenames: false
      - id: deny
        name: ❌ Check licenses
        entry: cargo deny check licenses
        language: system
        pass_filenames: false
ci:
    autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
    autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
