[book]
authors = ["Vincent Emonet <vincent.emonet@gmail.com>"]
language = "en"
multilingual = false
src = "./docs"
title = "✍️ Nanopub cross-platform toolkit ⚔️"
description = "A cross-platform Rust library to sign Nanopublications, with bindings to Python and JS (wasm)"

[build]
build-dir = "./target/doc"
create-missing = false

[output.html]
git-repository-url = "https://github.com/vemonet/nanopub-rs"
