[package]
name = "nanopub-cli"
version = "0.0.5"
description = """
A cross-platform CLI tool written in Rust to sign Nanopublications.
"""
repository = "https://github.com/vemonet/nanopub-rs/tree/main/cli"
authors.workspace = true
edition.workspace = true
readme.workspace = true
license-file.workspace = true
keywords.workspace = true
homepage.workspace = true
categories.workspace = true

[dependencies]
nanopub = { version = "0.0.5", path = "../lib" }
clap = { version = "4.4.8", features = ["derive"] }
