[package]
name = "nanopub_rs_py"
description = "Python bindings for the Nanopub rust toolkit"
repository = "https://github.com/vemonet/nanopub-rs/tree/main/python"
homepage = "https://github.com/vemonet/nanopub-rs"
version = "0.1.0"
edition = "2018"

[lib]
name = "nanopub_rs_py"
crate-type = ["cdylib"]

[dependencies]
nanopub_rs = { path = "../lib" }

[dependencies.pyo3]
version = "0.17.1"
features = ["extension-module"]
