
name: Tests

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - run: rustup component add clippy
      - run: cargo clippy --all --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          rustup update
          cargo install cargo-tarpaulin
      - run: cargo build --all-features
      - run: cargo test
        env:
          RUST_BACKTRACE: 1

  cov:
    name: Coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v4
      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin -p nanopub --verbose --all-features --workspace --timeout 120 --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          # token: ${{secrets.CODECOV_TOKEN}} # not required for public repos


  compare:
    name: Compare speed with java and python implementations
    runs-on: ubuntu-latest
    env:
      HYPERFINE_VERSION: '1.12.0'
      STABLE_PYTHON_VERSION: '3.12'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.STABLE_PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.STABLE_PYTHON_VERSION }}

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'

    - name: Install hyperfine
      run: |
        wget https://github.com/sharkdp/hyperfine/releases/download/v${HYPERFINE_VERSION}/hyperfine_${HYPERFINE_VERSION}_amd64.deb
        sudo dpkg -i hyperfine_${HYPERFINE_VERSION}_amd64.deb

    - name: Install java and python tools
      run: |
        pip install --upgrade nanopub
        wget -O nanopub.jar https://github.com/Nanopublication/nanopub-java/releases/latest/download/nanopub-1.47-jar-with-dependencies.jar

    - name: Install ourself
      run: cargo install --path cli
      # Build would go to target/release/nanopub

    - name: Benchmark
      run: |
        hyperfine -m 100 --warmup 10 --export-markdown benchmark.md \
          'java -jar nanopub.jar sign lib/tests/resources/simple1-rsa.trig -k lib/tests/resources/id_rsa' \
          'np sign lib/tests/resources/simple1-rsa.trig -k lib/tests/resources/id_rsa' \
          'nanopub-cli sign lib/tests/resources/simple1-rsa.trig -k lib/tests/resources/id_rsa'

    - name: Upload benchmark markdown
      uses: actions/upload-artifact@v3
      with:
        name: benchmark.md
        path: ./benchmark.md
